name: 'Flow Request Action'
description: 'Delivery flow request & response parsing action'
author: 'zezaeoh <zezaeoh@github.com>'
inputs:
  application:
    required: true
    description: 'application name that registered in ops-monster'
  flow:
    required: true
    description: 'available flow: staging, production, success, cancel'
  version:
    required: true
    description: 'version of delivery'
  branch:
    required: false
    description: 'branch name of delivery version'
  image:
    required: false
    description: 'docker image full name'
  image-tag:
    required: false
    description: 'tag of docker image'
  git-sha:
    required: false
    description: 'git sha string'
runs:
  using: 'node12'
  main: 'dist/index.js'
